name: task manager

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: Unit Test 1
          run: |
            cd tests
            python3 -m pytest task_manager_max_size_test.py

      - name: Unit Test 2
          run: |
            cd tests
            python3 -m pytest task_manager_fifo_test.py

      - name: Unit Test 3
          run: |
            cd tests
            python3 -m pytest task_manager_priority_test.py